/**
 *
 *  Registrations.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace sqlite3
{

class Registrations
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _chat_id;
        static const std::string _state;
        static const std::string _message_id;
        static const std::string _name;
        static const std::string _company;
        static const std::string _company_position;
        static const std::string _phrase;
        static const std::string _telegram_nickname;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Registrations(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Registrations(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Registrations(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Registrations() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int64_t &pId) noexcept;
    void setIdToNull() noexcept;

    /**  For column chat_id  */
    ///Get the value of the column chat_id, returns the default value if the column is null
    const int64_t &getValueOfChatId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getChatId() const noexcept;
    ///Set the value of the column chat_id
    void setChatId(const int64_t &pChatId) noexcept;

    /**  For column state  */
    ///Get the value of the column state, returns the default value if the column is null
    const int64_t &getValueOfState() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getState() const noexcept;
    ///Set the value of the column state
    void setState(const int64_t &pState) noexcept;

    /**  For column message_id  */
    ///Get the value of the column message_id, returns the default value if the column is null
    const int64_t &getValueOfMessageId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getMessageId() const noexcept;
    ///Set the value of the column message_id
    void setMessageId(const int64_t &pMessageId) noexcept;

    /**  For column name  */
    ///Get the value of the column name, returns the default value if the column is null
    const std::string &getValueOfName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getName() const noexcept;
    ///Set the value of the column name
    void setName(const std::string &pName) noexcept;
    void setName(std::string &&pName) noexcept;

    /**  For column company  */
    ///Get the value of the column company, returns the default value if the column is null
    const std::string &getValueOfCompany() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCompany() const noexcept;
    ///Set the value of the column company
    void setCompany(const std::string &pCompany) noexcept;
    void setCompany(std::string &&pCompany) noexcept;

    /**  For column company_position  */
    ///Get the value of the column company_position, returns the default value if the column is null
    const std::string &getValueOfCompanyPosition() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCompanyPosition() const noexcept;
    ///Set the value of the column company_position
    void setCompanyPosition(const std::string &pCompanyPosition) noexcept;
    void setCompanyPosition(std::string &&pCompanyPosition) noexcept;

    /**  For column phrase  */
    ///Get the value of the column phrase, returns the default value if the column is null
    const std::string &getValueOfPhrase() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPhrase() const noexcept;
    ///Set the value of the column phrase
    void setPhrase(const std::string &pPhrase) noexcept;
    void setPhrase(std::string &&pPhrase) noexcept;

    /**  For column telegram_nickname  */
    ///Get the value of the column telegram_nickname, returns the default value if the column is null
    const std::string &getValueOfTelegramNickname() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTelegramNickname() const noexcept;
    ///Set the value of the column telegram_nickname
    void setTelegramNickname(const std::string &pTelegramNickname) noexcept;
    void setTelegramNickname(std::string &&pTelegramNickname) noexcept;


    static size_t getColumnNumber() noexcept {  return 9;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Registrations>;
    friend drogon::orm::BaseBuilder<Registrations, true, true>;
    friend drogon::orm::BaseBuilder<Registrations, true, false>;
    friend drogon::orm::BaseBuilder<Registrations, false, true>;
    friend drogon::orm::BaseBuilder<Registrations, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Registrations>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> id_;
    std::shared_ptr<int64_t> chatId_;
    std::shared_ptr<int64_t> state_;
    std::shared_ptr<int64_t> messageId_;
    std::shared_ptr<std::string> name_;
    std::shared_ptr<std::string> company_;
    std::shared_ptr<std::string> companyPosition_;
    std::shared_ptr<std::string> phrase_;
    std::shared_ptr<std::string> telegramNickname_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[9]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[1])
        {
            sql += "chat_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "state,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "message_id,";
            ++parametersCount;
        }
        if(!dirtyFlag_[3])
        {
            needSelection=true;
        }
        if(dirtyFlag_[4])
        {
            sql += "name,";
            ++parametersCount;
        }
        if(!dirtyFlag_[4])
        {
            needSelection=true;
        }
        if(dirtyFlag_[5])
        {
            sql += "company,";
            ++parametersCount;
        }
        if(!dirtyFlag_[5])
        {
            needSelection=true;
        }
        if(dirtyFlag_[6])
        {
            sql += "company_position,";
            ++parametersCount;
        }
        if(!dirtyFlag_[6])
        {
            needSelection=true;
        }
        if(dirtyFlag_[7])
        {
            sql += "phrase,";
            ++parametersCount;
        }
        if(!dirtyFlag_[7])
        {
            needSelection=true;
        }
        if(dirtyFlag_[8])
        {
            sql += "telegram_nickname,";
            ++parametersCount;
        }
        if(!dirtyFlag_[8])
        {
            needSelection=true;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[8])
        {
            sql.append("?,");

        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace sqlite3
} // namespace drogon_model
