/**
 *
 *  Registrations.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Registrations.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string Registrations::Cols::_id = "id";
const std::string Registrations::Cols::_chat_id = "chat_id";
const std::string Registrations::Cols::_state = "state";
const std::string Registrations::Cols::_message_id = "message_id";
const std::string Registrations::Cols::_name = "name";
const std::string Registrations::Cols::_company = "company";
const std::string Registrations::Cols::_company_position = "company_position";
const std::string Registrations::Cols::_phrase = "phrase";
const std::string Registrations::Cols::_telegram_nickname = "telegram_nickname";
const std::string Registrations::primaryKeyName = "id";
const bool Registrations::hasPrimaryKey = true;
const std::string Registrations::tableName = "registrations";

const std::vector<typename Registrations::MetaData> Registrations::metaData_={
{"id","int64_t","integer",8,1,1,0},
{"chat_id","int64_t","integer",8,0,0,1},
{"state","int64_t","integer",8,0,0,1},
{"message_id","int64_t","integer",8,0,0,1},
{"name","std::string","text",0,0,0,1},
{"company","std::string","text",0,0,0,1},
{"company_position","std::string","text",0,0,0,1},
{"phrase","std::string","text",0,0,0,1},
{"telegram_nickname","std::string","text",0,0,0,1}
};
const std::string &Registrations::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Registrations::Registrations(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["chat_id"].isNull())
        {
            chatId_=std::make_shared<int64_t>(r["chat_id"].as<int64_t>());
        }
        if(!r["state"].isNull())
        {
            state_=std::make_shared<int64_t>(r["state"].as<int64_t>());
        }
        if(!r["message_id"].isNull())
        {
            messageId_=std::make_shared<int64_t>(r["message_id"].as<int64_t>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["company"].isNull())
        {
            company_=std::make_shared<std::string>(r["company"].as<std::string>());
        }
        if(!r["company_position"].isNull())
        {
            companyPosition_=std::make_shared<std::string>(r["company_position"].as<std::string>());
        }
        if(!r["phrase"].isNull())
        {
            phrase_=std::make_shared<std::string>(r["phrase"].as<std::string>());
        }
        if(!r["telegram_nickname"].isNull())
        {
            telegramNickname_=std::make_shared<std::string>(r["telegram_nickname"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 9 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            chatId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            state_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            messageId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            company_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            companyPosition_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            phrase_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            telegramNickname_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Registrations::Registrations(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            chatId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            state_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            messageId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            company_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            companyPosition_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            phrase_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            telegramNickname_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
}

Registrations::Registrations(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("chat_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["chat_id"].isNull())
        {
            chatId_=std::make_shared<int64_t>((int64_t)pJson["chat_id"].asInt64());
        }
    }
    if(pJson.isMember("state"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["state"].isNull())
        {
            state_=std::make_shared<int64_t>((int64_t)pJson["state"].asInt64());
        }
    }
    if(pJson.isMember("message_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["message_id"].isNull())
        {
            messageId_=std::make_shared<int64_t>((int64_t)pJson["message_id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("company"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["company"].isNull())
        {
            company_=std::make_shared<std::string>(pJson["company"].asString());
        }
    }
    if(pJson.isMember("company_position"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["company_position"].isNull())
        {
            companyPosition_=std::make_shared<std::string>(pJson["company_position"].asString());
        }
    }
    if(pJson.isMember("phrase"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["phrase"].isNull())
        {
            phrase_=std::make_shared<std::string>(pJson["phrase"].asString());
        }
    }
    if(pJson.isMember("telegram_nickname"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["telegram_nickname"].isNull())
        {
            telegramNickname_=std::make_shared<std::string>(pJson["telegram_nickname"].asString());
        }
    }
}

void Registrations::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            chatId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            state_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            messageId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            company_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            companyPosition_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            phrase_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            telegramNickname_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
}

void Registrations::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("chat_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["chat_id"].isNull())
        {
            chatId_=std::make_shared<int64_t>((int64_t)pJson["chat_id"].asInt64());
        }
    }
    if(pJson.isMember("state"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["state"].isNull())
        {
            state_=std::make_shared<int64_t>((int64_t)pJson["state"].asInt64());
        }
    }
    if(pJson.isMember("message_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["message_id"].isNull())
        {
            messageId_=std::make_shared<int64_t>((int64_t)pJson["message_id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("company"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["company"].isNull())
        {
            company_=std::make_shared<std::string>(pJson["company"].asString());
        }
    }
    if(pJson.isMember("company_position"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["company_position"].isNull())
        {
            companyPosition_=std::make_shared<std::string>(pJson["company_position"].asString());
        }
    }
    if(pJson.isMember("phrase"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["phrase"].isNull())
        {
            phrase_=std::make_shared<std::string>(pJson["phrase"].asString());
        }
    }
    if(pJson.isMember("telegram_nickname"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["telegram_nickname"].isNull())
        {
            telegramNickname_=std::make_shared<std::string>(pJson["telegram_nickname"].asString());
        }
    }
}

const int64_t &Registrations::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Registrations::getId() const noexcept
{
    return id_;
}
void Registrations::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
void Registrations::setIdToNull() noexcept
{
    id_.reset();
    dirtyFlag_[0] = true;
}
const typename Registrations::PrimaryKeyType & Registrations::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &Registrations::getValueOfChatId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(chatId_)
        return *chatId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Registrations::getChatId() const noexcept
{
    return chatId_;
}
void Registrations::setChatId(const int64_t &pChatId) noexcept
{
    chatId_ = std::make_shared<int64_t>(pChatId);
    dirtyFlag_[1] = true;
}

const int64_t &Registrations::getValueOfState() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(state_)
        return *state_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Registrations::getState() const noexcept
{
    return state_;
}
void Registrations::setState(const int64_t &pState) noexcept
{
    state_ = std::make_shared<int64_t>(pState);
    dirtyFlag_[2] = true;
}

const int64_t &Registrations::getValueOfMessageId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(messageId_)
        return *messageId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Registrations::getMessageId() const noexcept
{
    return messageId_;
}
void Registrations::setMessageId(const int64_t &pMessageId) noexcept
{
    messageId_ = std::make_shared<int64_t>(pMessageId);
    dirtyFlag_[3] = true;
}

const std::string &Registrations::getValueOfName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Registrations::getName() const noexcept
{
    return name_;
}
void Registrations::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[4] = true;
}
void Registrations::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[4] = true;
}

const std::string &Registrations::getValueOfCompany() const noexcept
{
    static const std::string defaultValue = std::string();
    if(company_)
        return *company_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Registrations::getCompany() const noexcept
{
    return company_;
}
void Registrations::setCompany(const std::string &pCompany) noexcept
{
    company_ = std::make_shared<std::string>(pCompany);
    dirtyFlag_[5] = true;
}
void Registrations::setCompany(std::string &&pCompany) noexcept
{
    company_ = std::make_shared<std::string>(std::move(pCompany));
    dirtyFlag_[5] = true;
}

const std::string &Registrations::getValueOfCompanyPosition() const noexcept
{
    static const std::string defaultValue = std::string();
    if(companyPosition_)
        return *companyPosition_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Registrations::getCompanyPosition() const noexcept
{
    return companyPosition_;
}
void Registrations::setCompanyPosition(const std::string &pCompanyPosition) noexcept
{
    companyPosition_ = std::make_shared<std::string>(pCompanyPosition);
    dirtyFlag_[6] = true;
}
void Registrations::setCompanyPosition(std::string &&pCompanyPosition) noexcept
{
    companyPosition_ = std::make_shared<std::string>(std::move(pCompanyPosition));
    dirtyFlag_[6] = true;
}

const std::string &Registrations::getValueOfPhrase() const noexcept
{
    static const std::string defaultValue = std::string();
    if(phrase_)
        return *phrase_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Registrations::getPhrase() const noexcept
{
    return phrase_;
}
void Registrations::setPhrase(const std::string &pPhrase) noexcept
{
    phrase_ = std::make_shared<std::string>(pPhrase);
    dirtyFlag_[7] = true;
}
void Registrations::setPhrase(std::string &&pPhrase) noexcept
{
    phrase_ = std::make_shared<std::string>(std::move(pPhrase));
    dirtyFlag_[7] = true;
}

const std::string &Registrations::getValueOfTelegramNickname() const noexcept
{
    static const std::string defaultValue = std::string();
    if(telegramNickname_)
        return *telegramNickname_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Registrations::getTelegramNickname() const noexcept
{
    return telegramNickname_;
}
void Registrations::setTelegramNickname(const std::string &pTelegramNickname) noexcept
{
    telegramNickname_ = std::make_shared<std::string>(pTelegramNickname);
    dirtyFlag_[8] = true;
}
void Registrations::setTelegramNickname(std::string &&pTelegramNickname) noexcept
{
    telegramNickname_ = std::make_shared<std::string>(std::move(pTelegramNickname));
    dirtyFlag_[8] = true;
}

void Registrations::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &Registrations::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "chat_id",
        "state",
        "message_id",
        "name",
        "company",
        "company_position",
        "phrase",
        "telegram_nickname"
    };
    return inCols;
}

void Registrations::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getChatId())
        {
            binder << getValueOfChatId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getState())
        {
            binder << getValueOfState();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getMessageId())
        {
            binder << getValueOfMessageId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCompany())
        {
            binder << getValueOfCompany();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCompanyPosition())
        {
            binder << getValueOfCompanyPosition();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getPhrase())
        {
            binder << getValueOfPhrase();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getTelegramNickname())
        {
            binder << getValueOfTelegramNickname();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Registrations::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    return ret;
}

void Registrations::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getChatId())
        {
            binder << getValueOfChatId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getState())
        {
            binder << getValueOfState();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getMessageId())
        {
            binder << getValueOfMessageId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCompany())
        {
            binder << getValueOfCompany();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCompanyPosition())
        {
            binder << getValueOfCompanyPosition();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getPhrase())
        {
            binder << getValueOfPhrase();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getTelegramNickname())
        {
            binder << getValueOfTelegramNickname();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Registrations::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getChatId())
    {
        ret["chat_id"]=(Json::Int64)getValueOfChatId();
    }
    else
    {
        ret["chat_id"]=Json::Value();
    }
    if(getState())
    {
        ret["state"]=(Json::Int64)getValueOfState();
    }
    else
    {
        ret["state"]=Json::Value();
    }
    if(getMessageId())
    {
        ret["message_id"]=(Json::Int64)getValueOfMessageId();
    }
    else
    {
        ret["message_id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getCompany())
    {
        ret["company"]=getValueOfCompany();
    }
    else
    {
        ret["company"]=Json::Value();
    }
    if(getCompanyPosition())
    {
        ret["company_position"]=getValueOfCompanyPosition();
    }
    else
    {
        ret["company_position"]=Json::Value();
    }
    if(getPhrase())
    {
        ret["phrase"]=getValueOfPhrase();
    }
    else
    {
        ret["phrase"]=Json::Value();
    }
    if(getTelegramNickname())
    {
        ret["telegram_nickname"]=getValueOfTelegramNickname();
    }
    else
    {
        ret["telegram_nickname"]=Json::Value();
    }
    return ret;
}

std::string Registrations::toString() const
{
    return toJson().toStyledString();
}

Json::Value Registrations::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 9)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getChatId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfChatId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getState())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfState();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getMessageId())
            {
                ret[pMasqueradingVector[3]]=(Json::Int64)getValueOfMessageId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[4]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getCompany())
            {
                ret[pMasqueradingVector[5]]=getValueOfCompany();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getCompanyPosition())
            {
                ret[pMasqueradingVector[6]]=getValueOfCompanyPosition();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getPhrase())
            {
                ret[pMasqueradingVector[7]]=getValueOfPhrase();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getTelegramNickname())
            {
                ret[pMasqueradingVector[8]]=getValueOfTelegramNickname();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getChatId())
    {
        ret["chat_id"]=(Json::Int64)getValueOfChatId();
    }
    else
    {
        ret["chat_id"]=Json::Value();
    }
    if(getState())
    {
        ret["state"]=(Json::Int64)getValueOfState();
    }
    else
    {
        ret["state"]=Json::Value();
    }
    if(getMessageId())
    {
        ret["message_id"]=(Json::Int64)getValueOfMessageId();
    }
    else
    {
        ret["message_id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getCompany())
    {
        ret["company"]=getValueOfCompany();
    }
    else
    {
        ret["company"]=Json::Value();
    }
    if(getCompanyPosition())
    {
        ret["company_position"]=getValueOfCompanyPosition();
    }
    else
    {
        ret["company_position"]=Json::Value();
    }
    if(getPhrase())
    {
        ret["phrase"]=getValueOfPhrase();
    }
    else
    {
        ret["phrase"]=Json::Value();
    }
    if(getTelegramNickname())
    {
        ret["telegram_nickname"]=getValueOfTelegramNickname();
    }
    else
    {
        ret["telegram_nickname"]=Json::Value();
    }
    return ret;
}

bool Registrations::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("chat_id"))
    {
        if(!validJsonOfField(1, "chat_id", pJson["chat_id"], err, true))
            return false;
    }
    else
    {
        err="The chat_id column cannot be null";
        return false;
    }
    if(pJson.isMember("state"))
    {
        if(!validJsonOfField(2, "state", pJson["state"], err, true))
            return false;
    }
    else
    {
        err="The state column cannot be null";
        return false;
    }
    if(pJson.isMember("message_id"))
    {
        if(!validJsonOfField(3, "message_id", pJson["message_id"], err, true))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(4, "name", pJson["name"], err, true))
            return false;
    }
    if(pJson.isMember("company"))
    {
        if(!validJsonOfField(5, "company", pJson["company"], err, true))
            return false;
    }
    if(pJson.isMember("company_position"))
    {
        if(!validJsonOfField(6, "company_position", pJson["company_position"], err, true))
            return false;
    }
    if(pJson.isMember("phrase"))
    {
        if(!validJsonOfField(7, "phrase", pJson["phrase"], err, true))
            return false;
    }
    if(pJson.isMember("telegram_nickname"))
    {
        if(!validJsonOfField(8, "telegram_nickname", pJson["telegram_nickname"], err, true))
            return false;
    }
    return true;
}
bool Registrations::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                       const std::vector<std::string> &pMasqueradingVector,
                                                       std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Registrations::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("chat_id"))
    {
        if(!validJsonOfField(1, "chat_id", pJson["chat_id"], err, false))
            return false;
    }
    if(pJson.isMember("state"))
    {
        if(!validJsonOfField(2, "state", pJson["state"], err, false))
            return false;
    }
    if(pJson.isMember("message_id"))
    {
        if(!validJsonOfField(3, "message_id", pJson["message_id"], err, false))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(4, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("company"))
    {
        if(!validJsonOfField(5, "company", pJson["company"], err, false))
            return false;
    }
    if(pJson.isMember("company_position"))
    {
        if(!validJsonOfField(6, "company_position", pJson["company_position"], err, false))
            return false;
    }
    if(pJson.isMember("phrase"))
    {
        if(!validJsonOfField(7, "phrase", pJson["phrase"], err, false))
            return false;
    }
    if(pJson.isMember("telegram_nickname"))
    {
        if(!validJsonOfField(8, "telegram_nickname", pJson["telegram_nickname"], err, false))
            return false;
    }
    return true;
}
bool Registrations::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Registrations::validJsonOfField(size_t index,
                                     const std::string &fieldName,
                                     const Json::Value &pJson,
                                     std::string &err,
                                     bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
